### ISSUE TITLE
Add Client ID and Client Secret Auth method

### ISSUE THREAD

**Issue by vperezb** [vperezb/google-api-support#2]
It's needed to add the Auth method that uses Client ID-Secret pair like in the [Slides Python Quickstart](https://developers.google.com/slides/quickstart/python) in a way that allows us to choose between auth methods.

___

Issue Background:

From the comment shared by @ladevan in https://github.com/vperezb/google-api-support/issues/1#issuecomment-584413819_

There's another Auth method that uses Client ID and Client Secret to give authorization to the program. It's the one used in the Python Slides Quickstart [here](https://developers.google.com/slides/quickstart/python), that doesn't require share documents with an email.

**Comment by vperezb** [comment]
I'm trying to create a layer on top of the APIs to allow users to authenticate and use simpler functions. 

As seen in Google Cloud Auth methods https://cloud.google.com/docs/authentication/ by now the module has implemented the `Service account key` Strategy.

This issue is intended to add now the `OAuth 2.0 client` Strategy

**Comment by ejh56** [comment]
Hey! I plan on using your library, but really need the OAuth capabilities. I see you are testing out with a jupyter notebook. If I make a pull request with a potential solution, would you consider merging it - or should I fork this project?

**Comment by vperezb** [comment]
Good morning @ejh56 , yes of course! I'm a bit busy those days, but absolutely will be amazing to merge a solution on the modules! Thanks in advance!

**Comment by vperezb** [comment]
You should have received the notification to allow you contribute on the repo, tell me if there's any issue! Thanks!

**Comment by vperezb** [comment]
This feature is avaliable in the `0.1.0` version.

PR: https://github.com/vperezb/google-api-support/pull/36
