### ISSUE TITLE
Copied file not accessible by personal account

### ISSUE THREAD

**Issue by silvia-ventoruzzo** [vperezb/google-api-support#28]
Hi @vperezb,
thanks a lot for developing this, it has a lot of useful functionalities.
The function `drive.copy_file()` successfully made a copy of my file, but this is not accessible by my personal account. I wonder if it's related to using service account credentials.
Not sure how to get around this.

**Comment by vperezb** [comment]
Hi there @silvia-ventoruzzo , 
Glad to see it's useful for more people! 
I'll take a look on that and see what can be done to fix it if that's the case 👍

**Comment by vperezb** [comment]
Hi again, I have few questions about the usecase:

Initial situaion:
You have a `project` with a `service_account` and its `service_account_credentials` tied to this `project`.  
Then, you as `user` have also access to that project by navigating in the `gcloud web client`.
The `document` you are trying to copy is in a folder in which your `user` has access and also shared with the `service_accounts_credentials`.

Observation:
When copied, the `document` should appear in the same folder than the original document with the same permisions.

Issue:
Seems like the copied `document` is not shared with the same person.

Possible inmediate solution: 
Maybe sharing the whole folder with the `service_account` solves this issue.

More elaborated solution:
Modifying or adding a function to enable sharing with pre-defined users, domains or group.
This function can, in the future be used by the copy function itself.

Tellme if that helped or if the usecase is correct so we can keep working on it if it's not the case!

**Comment by silvia-ventoruzzo** [comment]
Hi @vperezb,
thank you for the quick follow up!
The initial situation is as you described. Additional information: the service account has the role editor.
The immediate solution momentarily fixed the problem, but:
- initially my file was directly in the drive, so the solution wouldn't work in that case
- I think that if it would be possible to use the authentification method mentioned in https://github.com/vperezb/google-api-support/issues/1#issuecomment-584413819, then this would not happen

**Comment by vperezb** [comment]
This issue is been solved in PR #29 . 

It's still pending the resolution of issue #2 in addition to the `service account` authentication method that can also solve this issue.

Do you think it's better to close this issue or to keep it open until the other is solved?

**Comment by silvia-ventoruzzo** [comment]
Happy that I could be of help.

As the permissions issue is resolved, I think this issue can be closed and keep issue #1 and/or #2 for the alternative authentication method.

**Comment by vperezb** [comment]
> Happy that I could be of help.
> 
> As the permissions issue is resolved, I think this issue can be closed and keep issue #1 and/or #2 for the alternative authentication method.

You are welcome, any help to keep making the lib grow it's a gift! If you have any ideas on how to improve the repo (or make it more _professional_ don't hesitate to suggest it.

I'll try to solve the mentioned issue when I have time !

Thanks again

**Comment by silvia-ventoruzzo** [comment]
> You are welcome, any help to keep making the lib grow it's a gift! If you have any ideas on how to improve the repo (or make it more _professional_ don't hesitate to suggest it.
> 
> I'll try to solve the mentioned issue when I have time !
> 
> Thanks again

Hi @vperezb, sorry for writing you like this but I would love to continue contributing to the project. I see that you put a link to a discord chat, but it is not working (might be invalid or expired). Could you please check? Thanks!

**Comment by vperezb** [comment]
Yes sure, tell me if https://discord.gg/AcsDXgKJ works, if not we can check another way. (Y)
