### ISSUE TITLE
Ability to replace image from local file path

### ISSUE THREAD

**Issue by ericmanyc** [vperezb/google-api-support#43]
Currently, batch_replace_shape_with_image function requires an http link. It would be great if you can also allow local file path.

**Comment by vperezb** [comment]
Hi there @ericmanyc, thanks for sharing this use case, I'll take a look as soon as I can.

Meanwhile, I think you can use a combination of google drive library and Google Slides to achieve what you are looking for.

I've uploaded a notebook with some steps that you can adapt to achieve the result.

If you find a propper way to implement that within the "replace_shape_with_image" function itself, feel free to open a pull request. If not, I'll try to give it some time to implement it.

As said, here you have a quick workaround: https://github.com/vperezb/google-api-support/blob/master/docs/examples/upload_local_file_and_replace.ipynb

Hope it helps!

**Comment by ericmanyc** [comment]
Thank you very much for looking into this. I am away this week but will take a look soon. Great project by the way!

**Comment by ericmanyc** [comment]
@vperezb Works great for me! When are you planning to push another release ver? I am using hex tech for my environment and they require a release version.

**Comment by ericmanyc** [comment]
I was testing this function

`drive.delete_file(file_id=upload_response['file_id'])`

and it is returning an error. 

However 
`upload_response = drive.upload_image_to_drive('graph', r'./chart_screenshot.png', folder_id)

slides.replace_shape_with_image(upload_response['image_url'], PRESENTATION_ID, 'image_1')`

works.

I granted my service account email with content manager access to the folder in my drive.

**Comment by vperezb** [comment]
Good afternoon, 

Do you mean that after you used the upload function the following "delete" does not work because the file is not found?

Is there a chance that the issue is related to the "not-refreshing" Google Drive client? Here's an example:

Imagine you've uploaded the file and then deleted it successfully, you may still see the image in your folder in the drive web. Then you try to delete the image because visually is there but in reality, is because is not refreshed. When trying to delete the image the request will prompt the error.

I had some issues with that and sometimes happens.

**Comment by ericmanyc** [comment]
I dont believe so, when I upload_image_to_drive, I can see the file in my drive. However when I run drive.delete_file, it is stating "File not found: ***********************.".

**Comment by vperezb** [comment]
Understood, I'll try to copy the lanes you pasted to see if I can reproduce it.

Or if you can copy the full snippet or error trace to have more info to see if I can identify something 👍 

Thanks!

**Comment by ericmanyc** [comment]
This is the entire log
```

HttpError                                 Traceback (most recent call last)
/tmp/ipykernel_1/1679185493.py in <cell line: 4>()
      2 _hex_pks.kernel_execution.scope_watcher.mark_dirty_scope_items(args=_hex_types.MarkDirtyScopeItemsArgs.from_dict({**_hex_json.loads("{\"dirty_scope_items\":[\"drive\",\"upload_response\"]}")}), app_session_token=_hex_APP_SESSION_TOKEN, python_kernel_init_status=_hex_python_kernel_init_status, hex_timezone=_hex_kernel.variable_or_none("hex_timezone", scope_getter=lambda: globals()))
      3 
----> 4 drive.delete_file(file_id=upload_response['file_id'])

~/.cache/pypoetry/virtualenvs/python-kernel-OtKFaj5M-py3.9/lib/python3.9/site-packages/GoogleApiSupport/drive.py in delete_file(file_id)
    116 def delete_file(file_id):
    117     service = auth.get_service("drive")
--> 118     response = service.files().delete(fileId=file_id).execute()
    119     print(f"Deleted file: {file_id}")
    120     return response

~/.cache/pypoetry/virtualenvs/python-kernel-OtKFaj5M-py3.9/lib/python3.9/site-packages/googleapiclient/_helpers.py in positional_wrapper(*args, **kwargs)
    128                 elif positional_parameters_enforcement == POSITIONAL_WARNING:
    129                     logger.warning(message)
--> 130             return wrapped(*args, **kwargs)
    131         return positional_wrapper
    132 

~/.cache/pypoetry/virtualenvs/python-kernel-OtKFaj5M-py3.9/lib/python3.9/site-packages/googleapiclient/http.py in execute(self, http, num_retries)
    838       callback(resp)
    839     if resp.status >= 300:
--> 840       raise HttpError(resp, content, uri=self.uri)
    841     return self.postproc(resp, content)
    842 

HttpError: <HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/*******************************? returned "File not found: *******************************.">


```
