### ISSUE TITLE
slides.get_slide_notes error

### ISSUE THREAD

**Issue by ldnelso2** [vperezb/google-api-support#45]
I am noticing an issue here with the slides get_slide_notes method.  When I use this method, I'm getting an error.  "# Error in slide'slideProperties'"

The method itself has a reference to a slideProperties key (shown in bold), which doesn't appear to be my slide dict.

def get_slide_notes(slide_object: dict):
    output = []
    try:
        **for element in slide_object['slideProperties']['notesPage']['pageElements']:**
            if 'shapeType' in element['shape'] and element['shape']['shapeType'] == 'TEXT_BOX':
                for line in element['shape']['text']['textElements'][1::2]:
                    if 'textRun' in line:
                        output += [line['textRun']['content']]
        return ''.join(output)
    except Exception as e:
        return '# Error in slide' + str(e)

**The slides dict is really long, but to get the keys, I tried this:** 
def get_slide_notes(slide_object: dict):
    print("Debug: slide_object keys are:", slide_object.keys())  # Add this line for debugging
    output = []
    try:
        for element in slide_object['slideProperties']['notesPage']['pageElements']:
            if 'shapeType' in element['shape'] and element['shape']['shapeType'] == 'TEXT_BOX':
                for line in element['shape']['text']['textElements'][1::2]:
                    if 'textRun' in line:
                        output += [line['textRun']['content']]
        return ''.join(output)
    except Exception as e:
        return '# Error in slide' + str(e)

This returns:  Debug: slide_object keys are: dict_keys(['presentationId', 'pageSize', 'slides', 'title', 'masters', 'layouts', 'locale', 'revisionId', 'notesMaster'])

So, if I re-write it using 'slides' as the key, it works: 

def extract_notes_from_presentation(presentation_data):
    all_notes = []
    # Check if 'slides' key exists in the presentation data
    if 'slides' in presentation_data:
        for slide in presentation_data['slides']:
            notes = get_slide_notes(slide)
            all_notes.append(notes)
    else:
        all_notes.append('No slides found in presentation data')
    return all_notes

def get_slide_notes(slide_object: dict):
    output = []
    try:
        # Navigate through the correct keys to reach the notes text elements
        for element in slide_object['slideProperties']['notesPage']['pageElements']:
            if 'shapeType' in element['shape'] and element['shape']['shapeType'] == 'TEXT_BOX':
                for line in element['shape']['text']['textElements'][1::2]:
                    if 'textRun' in line:
                        output += [line['textRun']['content']]
        return ''.join(output)
    except Exception as e:
        return '# Error in slide: ' + str(e)

### this returns the content of my speaker notes from the target Google Slides file's dict.  

I'm not quite sophisticated enough to do a pull request here or know if this is a replicable problem for others, but I am willing to try.  

Thanks!

**Comment by vperezb** [comment]
Many thanks for writing! I'll review it and upload the fix asap!

**Comment by vperezb** [comment]
I reviewed the code and used it in a notebook and I've been unsuccessful in replicating your use case, I've created a new page in /docs to show how I use both the new and old functions.

https://github.com/vperezb/google-api-support/blob/master/docs/examples/extracting-slides-notes.ipynb

If you can take a look and check if that works on your scenario that'd be nice, if that didn't work I'll be glad to review it further to fix it properly.

Many thanks!
