### ISSUE TITLE
Replace Placeholder text with Shape?

### ISSUE THREAD

**Issue by sharathsridhar** [vperezb/google-api-support#7]
Hello @vperezb Looking for ideas here, because I believe this is not present in the google documentation - Is there a way we can replace placeholder text (for example - {{1}}) with a shape (for example an up arrow)? If this is not possible, how do we send a shape request and where will it actually reside in the presentation?

Sorry, was getting confused when reading https://developers.google.com/slides/api/reference/rest/v1/presentations/request

**Comment by vperezb** [comment]
Hi there @sharathsridhar, before diving into the documentation (I'll doit after writing you) I'll give you a quick answer and if not suits your needs I'll try to seek further.

Is there a way we can replace placeholder text (for example - {{1}}) with a shape (for example an up arrow)?
- By now I can think about creating the arrows as images and make a [ImageReplace](https://developers.google.com/slides/api/reference/rest/v1/presentations/request#imagereplacemethod) 
- (Not tested) You can use the [UpdateShapePropertiesRequest](https://developers.google.com/slides/api/reference/rest/v1/presentations/request#updateshapepropertiesrequest) and use it to modify the reference shape you use as a placeholder 
[Shape Type](https://developers.google.com/slides/api/reference/rest/v1/presentations.pages/shapes#Page.Type)
- If it suits you needs, you can use an actual ASCII arrow character and use it as normal text with the replace text solutions already known ([ASCII Arrows](https://unicode-table.com/en/sets/arrow-symbols/))

I'll take a look when possible to the shape management requests and I'll try to create an easy interface to create them, they might work using the whole slide as a chord system and using relative positions you can give a (x,y) to insert the shape. I need to check on it!

Thanks for taking your time taking a look into the lib!
V

**Comment by vperezb** [comment]
I created this notebook showing the usage of these new functions.

https://github.com/vperezb/google-api-support/blob/master/docs/examples/Changing%20shape%20types%20using%20Google%20Slides%20API%20(workaround).ipynb 

The functions are very generic to allow usage in other use cases and at some point, the performance can be improved.
Hope it's useful for your use case!

**Comment by sharathsridhar** [comment]
@vperezb Wow, this is great! I will test it out and let you know if I run into more issues! Thank you for looking into this so quickly!

**Comment by vperezb** [comment]
Your welcome! To make sure I didn't break anything previous I've released it in the `0.0.5b2` pre-release version. You can install it and test it by doing `pip install google-api-support==0.0.5b2` .
Tellme if it suits!
